FROM golang:1.18.7
ARG VER="v0.1.11"
WORKDIR /go/src
RUN git clone --branch ${VER} https://github.com/fefit/fetc && cd ./fetc/ && go build && cp ./fetc /go/bin/fetc && chmod a+x /go/bin/fetc
ENTRYPOINT [ "/go/bin/fetc" ]
CMD ["-h"]